version: '3'

services:
    alice-agent:
        command: ['alice --port 8030 --aip 10']
        build:
            context: ../aries-cloudagent-python
            dockerfile: ./docker/Dockerfile05022024.demo
        ports:
            - 8030-8037:8030-8037
        networks:
            - von_von
        # network_mode: host
        environment:
            - RUNMODE=${RUNMODE}
            - DOCKERHOST=${DOCKERHOST}
            - LEDGER_URL=${LEDGER_URL}
            - GENESIS_URL=${GENESIS_URL}
        tty: true
    alice-controller:
        build:
            context: ../controllers/alice-controller/
            args:
                - RUNMODE=${RUNMODE}
                - ALICE_AGENT_HOST=host.docker.internal
        ports:
            - 9031:80
        networks:
            - von_von
        # network_mode: host
        depends_on:
            - alice-agent

networks:
  von_von:
    external: true